emprecordapp/emp/urls.py
from django.contrib import admin
from django.urls import path
from employee import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),
    path('show', views.show),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.destroy),
]

emprecordapp/employee/models.py
from django.db import models


class Employee(models.Model):
    emp_id = models.CharField(max_length=20)
    emp_name = models.CharField(max_length=100)
    emp_email = models.EmailField()
    emp_contact = models.CharField(max_length=15)

    class Meta:
        db_table = "employee"

emprecordapp/employee/forms.py
from django import forms  
from employee.models import Employee


class EmployeeForm(forms.ModelForm): 
    class Meta:  
        model = Employee
        fields = "__all__"

emprecordapp/employee/views.py
from django.shortcuts import render, redirect
from employee.forms import EmployeeForm
from employee.models import Employee


def emp(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST)

        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form = EmployeeForm()
    return render(request, "index.html", {'form':form})


def show(request):
    employees = Employee.objects.all()
    return render(request, "show.html", {'employees':employees})


def edit(request, id):
    employee = Employee.objects.get(id=id)
    return render(request, "edit.html", {'employee':employee})


def update(request, id):
    employee = Employee.objects.get(id=id)
    form = EmployeeForm(request.POST, instance=employee)

    if form.is_valid():
        form.save()
        return redirect("/show")

    return render(request, "edit.html", {'employee':employee})


def destroy(request, id):
    employee = Employee.objects.get(id=id)
    employee.delete()
    return redirect("/show")

emprecordapp/employee/templates/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Edit</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha256-YLGeXaapI0/5IgZopewRJcFXomhRMlYYjugPLSyNjTY=" crossorigin="anonymous" />
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container py-5">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" class="post-form" action="/update/{{ employee.id }}">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-7 mx-auto">
                                    <h3 class="text-center">Update Details</h3>
                                    <hr>
                                    <div class="form-group row">
                                        <label for="" class="col-sm-4 col-form-label">Employee Id:</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="emp_id" id="id_emp_id" required maxlength="20" value="{{ employee.emp_id }}"/>  
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="" class="col-sm-4 col-form-label">Employee Name:</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="emp_name" id="id_emp_name" required maxlength="100" value="{{ employee.emp_name }}" /> 
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="" class="col-sm-4 col-form-label">Employee Email:</label>
                                        <div class="col-sm-8">
                                            <input type="email" class="form-control" name="emp_email" id="id_emp_email" required maxlength="254" value="{{ employee.emp_email }}" />  
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="" class="col-sm-4 col-form-label">Employee Contact:</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="emp_contact" id="id_emp_contact" required maxlength="15" value="{{ employee.emp_contact }}" />  
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="" class="col-sm-4 col-form-label"></label>
                                        <div class="col-sm-8">
                                            <button type="submit" class="btn btn-success btn-lg btn-block text-uppercase">Update</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha256-CjSoeELFOcH0/uxWu6mC/Vlrc1AARqbm/jiiImDGV3s=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha256-fTuUgtT7O2rqoImwjrhDgbXTKUwyxxujIMRIK7TbuNU=" crossorigin="anonymous"></script>
</body>
</html>

emprecordapp/employee/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Index</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha256-YLGeXaapI0/5IgZopewRJcFXomhRMlYYjugPLSyNjTY=" crossorigin="anonymous" />
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container py-5">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" class="post-form" action="/emp">
                            {% csrf_token %}
                            <div class="container">
                                <div class="row">
                                    <div class="col-7 mx-auto">
                                        <h3 class="text-center">Enter Details</h3>
                                        <hr>
                                        <div class="form-group row">
                                            <label for="" class="col-sm-4 col-form-label">Employee Id:</label>
                                            <div class="col-sm-8">
                                                <!-- {{ form.emp_id }} -->
                                                <input type="text" class="form-control" name="emp_id" id="id_emp_id" required maxlength="20" value="{{ employee.emp_id }}"/>
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="" class="col-sm-4 col-form-label">Employee Name:</label>
                                            <div class="col-sm-8">
                                                <!-- {{ form.emp_name }} -->
                                                <input type="text" class="form-control" name="emp_name" id="id_emp_name" required maxlength="100" value="{{ employee.emp_name }}" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="" class="col-sm-4 col-form-label">Employee Email:</label>
                                            <div class="col-sm-8">
                                                <!-- {{ form.emp_email }} -->
                                                <input type="email" class="form-control" name="emp_email" id="id_emp_email" required maxlength="254" value="{{ employee.emp_email }}" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="" class="col-sm-4 col-form-label">Employee Contact:</label>
                                            <div class="col-sm-8">
                                                <!-- {{ form.emp_contact }} -->
                                                <input type="text" class="form-control" name="emp_contact" id="id_emp_contact" required maxlength="15" value="{{ employee.emp_contact }}" />
                                            </div>
                                        </div>
                                        <div class="form-group row">
                                            <label for="" class="col-sm-4 col-form-label"></label>
                                            <div class="col-sm-8">
                                                <button type="submit" class="btn btn-primary btn-lg text-uppercase btn-block">Submit</button>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha256-CjSoeELFOcH0/uxWu6mC/Vlrc1AARqbm/jiiImDGV3s=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha256-fTuUgtT7O2rqoImwjrhDgbXTKUwyxxujIMRIK7TbuNU=" crossorigin="anonymous"></script>
</body>
</html>

emprecordapp/employee/templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Employee Records</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha256-YLGeXaapI0/5IgZopewRJcFXomhRMlYYjugPLSyNjTY=" crossorigin="anonymous" />
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" integrity="sha256-+N4/V/SbAFiW1MPBCXnfnP9QSN3+Keu+NlB+0ev/YKQ=" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container py-5">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <table class="table table-striped table-bordered">
                            <thead class="thead-dark">
                                <tr>
                                    <th>Employee ID</th>
                                    <th>Employee Name</th>
                                    <th>Employee Email</th>
                                    <th>Employee Contact</th>
                                    <th class="text-center">Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for employee in employees %}  
                                <tr>
                                    <td>{{ employee.emp_id }}</td>
                                    <td>{{ employee.emp_name }}</td>
                                    <td>{{ employee.emp_email }}</td>
                                    <td>{{ employee.emp_contact }}</td>
                                    <td class=text-center>
                                        <a href="/edit/{{ employee.id }}" title="Edit" class="px-2"><i class="fas fa-pencil-alt"></i></a>
                                        <a href="/delete/{{ employee.id }}" title="Delete" class="px-2"><i class="fas fa-trash-alt"></i></a>  
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <p class="text-center pt-5 mb-0">
                            <a href="/emp" class="btn btn-primary btn-lg text-uppercase">Add New Record</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha256-CjSoeELFOcH0/uxWu6mC/Vlrc1AARqbm/jiiImDGV3s=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.15.0/umd/popper.min.js" integrity="sha256-fTuUgtT7O2rqoImwjrhDgbXTKUwyxxujIMRIK7TbuNU=" crossorigin="anonymous"></script>
</body>
</html>